title: rootðŸ’€Sp3c7r4:~#
description: Hack Eat Commit Push Sleep Repeat!
show_downloads: false
github: [metadata]
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
# baseurl: /SP3C7R4.GITHUB.IO